servers:
  - domain: localhost
    routes:
      - path: /api/v1/**
        type: proxy
        rate_limit: 10
        rate_window: 5           
        backends:
          - http://localhost:8080
          - http://localhost:8081